#!/bin/bash

echo "Hello!"

read -rp "What is your name?" name  

echo "Hello $name!"

if [ "$name" = "Sam" ] || [ "$name" = "sam" ]
then echo "You're really good at coding :)"
else echo "Whooooooooooo are you?"
fi

exit 1
